server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:13306/news?serverTimezone=UTC&useSSL=true&autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1  # HikariCP 유효성 검사 추가
      validation-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create  # 오직 테스트 환경에서만
    generate-ddl: true   # 오직 테스트 환경에서만 (spring.jpa.generate-ddl)
    show-sql: true
    open-in-view: false

  ai:
    openai:
      api-key: ${OPEN_AI_API_KEY}
      chat:
        options:
          model: ${AI_MODEL}

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # 하트비트 간격(기본 30초)
    lease-expiration-duration-in-seconds: 30 # 만료 시간(기본 90초)
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

naver:
  client:
    id: ${NAVER_CLIENT_ID}
  search:
    key: ${NAVER_SEARCH_KEY}