apiVersion: v1
kind: Secret
metadata:
  name: news-secret
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
    
      ai:
        openai:
          api-key: ${OPEN_AI_API_KEY}
          base-url: https://api.groq.com/openai/v1
          chat:
            options:
              model: ${AI_MODEL}
   
    naver:
      client:
        id: ${NAVER_CLIENT_ID}
      search:
        key: ${NAVER_SEARCH_KEY}