apiVersion: v1
kind: Secret
metadata:
  name: news-secret
stringData:
  application-secret.yml: |
    spring:
      datasource:
        username: user
        password: 1234
    
      ai:
        openai:
          api-key: ${OPEN_AI_API_KEY}
          chat:
            options:
              model: ${AI_MODEL}
    jwt:
      expires-in: 86400 # 1day
      mobile-expires-in: 31536000
      tablet-expires-in: 31536000
      secret-key: AADfaskllewadfaeradfadfaeradfadgaadfadfadfadfadfadfasdfafgdfgaer38GsWg86G  
    
    naver:
      client:
        id: ${NAVER_CLIENT_ID}
      search:
        key: ${NAVER_SEARCH_KEY}