apiVersion: v1
kind: Service
metadata:
  name: news-mysql-service
spec:
  ports:
    - port: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: news-mysql-service
subsets:
  - addresses:
      - ip: 192.168.0.14 #각자의 ip
    ports:
      - port: 13308