apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      volumes:
        - name: news-config-volume
          configMap:
            name: news-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: backend-post-secret-volume
          secret:
            secretName: news-secret
            items:
              - key: application-secret.yml
                path: application-secret.yml
      containers:
        - name: news-service
          image: parangg/news-service:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /backend/post/v1/k8s/liveness  # 스프링 부트 생존 상태 엔드포인트
#              port: 8080
#            initialDelaySeconds: 30   # 컨테이너 시작 후 첫 검사까지 대기
#            periodSeconds: 5          # 5초마다 체크
#            failureThreshold: 3       # 3회 연속 실패 시 컨테이너 재시작
#            timeoutSeconds: 3         # 3초 내 응답 필요
#
#            # Readiness Probe 추가 (트래픽 유입 제어용)
#          readinessProbe:
#            httpGet:
#              path: /backend/post/v1/k8s/readiness  # 스프링 부트 준비 상태 엔드포인트
#              port: 8080
#            initialDelaySeconds: 30   # 컨테이너 시작 후 첫 검사까지 대기
#            periodSeconds: 5          # 5초마다 체크
#            failureThreshold: 3       # 3회 연속 실패 시 서비스 트래픽 중지
#            timeoutSeconds: 3  # 3초 내 응답 필요

          volumeMounts:
            - mountPath: /etc/config
              name: news-config-volume
              readOnly: true
            - mountPath: /etc/secret
              name: news-secret-volume
              readOnly: true